<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-15 at 13:40:10.
 */
class ConnectionTest extends \PHPUnit_Extensions_Database_TestCase {
    use Fixtures;
    /**
     * @var Connection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Connection;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Connection::pdo
     * @todo   Implement testPdo().
     */
    public function testPdo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Connection::setExceptionToBeReported
     * @todo   Implement testSetExceptionToBeReported().
     */
    public function testSetExceptionToBeReported() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Connection::unSetExceptionToBeReported
     * @todo   Implement testUnSetExceptionToBeReported().
     */
    public function testUnSetExceptionToBeReported() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Connection::pdoStatement
     * @todo   Implement testPdoStatement().
     */
    public function testPdoStatement() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Connection::execute
     * @todo   Implement testExecute().
     */
    public function testExecute() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Connection::__call
     * @todo   Implement test__call().
     */
    public function test__call() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
